### ISSUE TITLE
scs is null error when starting Sitecore Sidekick

### ISSUE THREAD

**Issue by victorantos** [JeffDarchuk/SitecoreSidekick#1]
I've installed it via Nuget

https://www.nuget.org/packages/SitecoreSidekickCore/1.2.0-alpha3
(plus all other SitecoreSidekick packages)

but I cannot run it 

```
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at eval (eval at scSitecore.process (Sitecore.js:937), <anonymous>:1:67)
```

I think `scs` is null. Why is it `null`?

![image](https://cloud.githubusercontent.com/assets/2494556/24303952/bc8a2db0-10af-11e7-8dc7-da6102c47cd3.png)

 

I am running Sitecore 7.2

**Comment by JeffDarchuk** [comment]
If everything installed properly, you should have 4 DLLs in your bin directory
ScsAuditLog.dll
ScsContentMigrator.dll
ScsEditingContext.dll
SitecoreSidekick.dll

and 4 config files
zSCS.config
zScsAuditLog.config
zSCSContentMigrator.config
zSCSEditingContext.config

I just successfully installed this on a SC 7.2 rev 160123 instance and it's working fine for me.  Do you see anything noteworthy in your Sitecore logs?

**Comment by victorantos** [comment]
Yes, I 've got all the required files

ScsAuditLog.dll
ScsContentMigrator.dll
ScsEditingContext.dll
SitecoreSidekick.dll

and 4 config files
zSCS.config
zScsAuditLog.config
zSCSContentMigrator.config
zSCSEditingContext.config

**Comment by JeffDarchuk** [comment]
That's to be expected, all assets are embedded into DLLs for a streamlined installation/deletion.  Any path that starts with /scs/ is routed through sidekick.  Did you check your logs?  Sometimes a 404 within sidekick will report errors in your Sitecore logs.

**Comment by victorantos** [comment]
I guess the SCS handler is not working, I noticed it's not shown here

![image](https://cloud.githubusercontent.com/assets/2494556/24401547/c0051130-13ac-11e7-8091-92711926c369.png)

**Comment by kamsar** [comment]
Suspect this might be to do with ordering in the MVC route table.

**Comment by JeffDarchuk** [comment]
Based on kamsar's suggestion I've pushed out an updated version which should inject the SCS route at the beginning of the route table.  This should prevent anything matching a route that starts with /scs/ before it makes it to sidekick.  Update your sidekick nuget package to alpha6 and give it a try.

**Comment by victorantos** [comment]
thanks for quick reply

I still get 404 error

![image](https://cloud.githubusercontent.com/assets/2494556/24412330/1578e4a2-13d0-11e7-82a5-fa781306b45b.png)

**Comment by JeffDarchuk** [comment]
Do you get anything when you go to {yourdomain}/scs/scs.scs

**Comment by victorantos** [comment]
I get `404` error for everything that starts with `/scs/`

**Comment by JeffDarchuk** [comment]
Hmm, yours is an interesting problem here.  Is there any more information about your setup you can give to me to reproduce this error?

Only things i can think of are either you're missing handlers for MVC routing or there is an error upon initialization that's causing the routes to not bind properly.

Did you check your Sitecore log for errors?  Perhaps we can see what's failing on init.

**Comment by victorantos** [comment]
There are no error on init. How can I check the MVC routing that is working properly?

**Comment by JeffDarchuk** [comment]
To be honest unfortunately i'm not very familiar with setting up MVC or debugging routing issues.  Without being able to reproduce this myself and try a few things i'm at a loss.  Last remaining thing i can think of would be to use Sitecore SIM to create a stock instance of the same version and revision you're using and compare the web.config file to make sure your site has all the required assemblies referenced.

**Comment by victorantos** [comment]
I've installed an new SC72 instance, and when I try to intall Sidekick via Nuget I get 

`Failed to add reference to 'HtmlDiff'.` and nothing is installed

**Comment by JeffDarchuk** [comment]
Did you install using nuget?  If not there're a few dependencies you need to take into consideration HtmlDiff is one of those.

**Comment by victorantos** [comment]
I managed to install ver `1.0.1` on new SC7.2, the pre-release was failing with some Rainbow error.

**Comment by JeffDarchuk** [comment]
Ah, i likely need to update those nuget package dependencies.  Thanks for pointing that out.  That's why we have pre-release.  Any luck comparing configurations?

**Comment by kamsar** [comment]
Based on https://github.com/JeffDarchuk/SitecoreSidekick/blob/master/ContentMigrator/ScsContentMigrator.nuspec#L21 I'd say the dependency is at least updated to the current HtmlDiff.

If you're seeing a Rainbow error still, can you provide any details there? I've run the current SCS 1.2 alpha against the current Rainbow 2 prerelease without issue; the APIs are stable that SCS is using.

**Comment by JeffDarchuk** [comment]
haven't heard any updates in a long while, closing

**Comment by tomunderhill** [comment]
I also hit this problem. IIS was directing the .js request to the static file handler. I added the following to web.config to get around it:

`<location path="scs">
    <system.webServer>
      <handlers>
        <add name="nostaticfile" path="*" verb="GET" type="System.Web.Handlers.TransferRequestHandler" />
      </handlers>
    </system.webServer>
  </location>`

I also have had to edit scscommand.js to move the document.body call at the bottom inside the window.onload.

(This was all on Sitecore 7.2 (rev. 151021))

**Comment by Piepenbrink** [comment]
Hi Jeff,

Recently ran in to this issue as well while upgrading a platform from 8.x to 10.1.

At first i thought it might be something with the custom code/config so i tried a clean 10.1 install with only sidekick (1.6.1). even left the configs vanilla that come with the nuget core package. Seems that the problem is occurring there as well. Went over the logs but don't see any errors on init. 

Have you since found any indication why the routeregistration would fail?

**Comment by Piepenbrink** [comment]
Thanks for the tip Jeff, that was indeed what was happening. After disabling the ContentMigrator config everything worked like a charm. I think i recreated the customizations in the new server config after upgrading to 1.6.1 but i must have forgotten to migrate the Shared secret. I feel like the stupidest person alive! 
What i would have expected though is that i would see the errors from the ContentMigrationRegistration (InvalidOperationException) popping up in the logs. Might be good to include and avoid having to spent time on people like me...

**Comment by JeffDarchuk** [comment]
you're absolutely correct.  It should be throwing errors into the logs, i'll make sure to do so in a future update.  Glad you got it figured out though!
